version: "3.8"
services:
  backend:
    image: "medinar/fullstack-spring-boot-react:28.10.2021.5.11.42"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev