version: "3.8"
services:
  backend:
    image: "medinar/fullstack-spring-boot-react:6.11.2021.9.25.19"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev