version: "3.8"
services:
  backend:
    image: "medinar/fullstack-spring-boot-react:7.11.2021.5.0.9"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev