version: "3.8"
services:
  backend:
    image: "medinar/fullstack-spring-boot-react:31.10.2021.22.15.55"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev